### ISSUE TITLE
colorspace issues with gltf/glb format

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#302]
Gltf color does not translate properly in interface.  When compared to an fbx of the same model it will appear slightly darker and less saturated in some cases.

![79605032-0b40a800-80a4-11ea-8b6e-a2b4c5bc462e 1](https://user-images.githubusercontent.com/21160271/79622045-85842300-80ca-11ea-9d5f-12f6f0e97eac.jpg)

In the example, fbx is on the left, gltf on the right.
[fbx](https://aitolda.s3.amazonaws.com/FreeAgentSource/Island/PalmVertexOnly3.fbx)
[gltf](https://aitolda.s3.amazonaws.com/FreeAgentSource/Island/PalmVertexOnly3.glb)

**Comment by kasenvr** [comment]
This issue has been fixed. :)

**Comment by kasenvr** [comment]
This issue has not been fixed, I mistook #545 for the solution. :)

Pic from Aitolda:
![image](https://user-images.githubusercontent.com/52365539/92419458-add4f280-f13b-11ea-8730-6b2cce0eabf3.png)

**Comment by ctrlaltdavid** [comment]
Do the colours of those two models look the same in a 3rd party viewer? I tried downloading and viewing them in Windows' built-in 3D Viewer program but only the GLB file is coloured. (The FBX renders as grey scale.) Similarly for Windows' Paint3D program. ... I surmise that the FBX file uses external textures.

**Comment by Aitolda** [comment]
Revisted. This issues still exist as of Vircadia 2021.1.0 Eos.  However we are considering witch to [ASSIMP](https://www.assimp.org/) which may solve many of these issues.

**Comment by ctrlaltdavid** [comment]
The colour test in the following issue should be useful: https://github.com/vircadia/vircadia/issues/957
