### ISSUE TITLE
Create domain ID loads indefinitely

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#770]
After adding a name to the Create domain ID dialogue, it loads indefinitely. I put ``MotoApartment`` in.

![2020-10-01 11 28 47 192 168 1 12 cb3bd452df18](https://user-images.githubusercontent.com/11144627/94792590-7a535400-03d9-11eb-8626-42fc5981c161.png)

**Comment by JulianGro** [comment]
![Uploading 1Auswahl_765.png…]()

**Comment by JulianGro** [comment]
![Uploading 1Auswahl_765.png…]()

**Comment by JulianGro** [comment]
![1Auswahl_765](https://user-images.githubusercontent.com/11144627/94864280-06966300-043c-11eb-9aa7-e8ea1bcab5f4.png)

**Comment by JulianGro** [comment]
![1Auswahl_766](https://user-images.githubusercontent.com/11144627/94864411-38a7c500-043c-11eb-84e1-e581e19b0ab4.png)

**Comment by kasenvr** [comment]
Possible repro: someone try to get this issue with a non-admin account? This issue was created using Master and the latest Metaverse API build, so unsure why it's failing only sometimes.

**Comment by JulianGro** [comment]
Apparently you cannot use "Create new domain ID". You can use "Get temporary place name" and that also creates a domain ID for you.

**Comment by kasenvr** [comment]
If you delete your config.json file, does this solve the problem?

**Comment by JulianGro** [comment]
Tried that before. Did something change that would make it worth testing again?

**Comment by kasenvr** [comment]
Not particularly, I was able to connect another server (Amazon Linux 2) last night without issue, the only difference I'm sensing between me and you would be admin rights, so I'm thinking this could be a permission problem.

**Comment by Misterblue** [comment]
This was fixed in Iamus 2.2.12 where it does create a new domainID and assigns it the input label as the name of the new domain. It doesn't completely work because, requesting the new domainId causes the domain-server to restart and the domain-server asks for a new temporary name (does POST /api/v1/domains/temporary) which assigns a new domain name and domainId to the domain.

The domain logic shouldn't be requesting a temporary domain name if the information is already in the config.json, so I'm not totally sure why this is failing in this manner.

**Comment by kasenvr** [comment]
Ah, so then yes please try again @JulianGro. If the domain-server is still doing weirdness, we can take a look at that as well.

**Comment by kasenvr** [comment]
Might be fixed in #803

**Comment by JulianGro** [comment]
Still happens for me. But also I am unsure why I would do that.

**Comment by JulianGro** [comment]
This has been fixed. I retested on 2020.3.2
